Traceback (most recent call last):
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/killiansheriff/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
r = s2_grid()
tp = o3.ElementwiseTensorProduct("1o", "1o", ['2e'], irrep_normalization='norm')
y2 = tp(r, r)
fig = plot(y2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m r [38;5;241m=[39m [43ms2_grid[49m()
[1;32m      2[0m tp [38;5;241m=[39m o3[38;5;241m.[39mElementwiseTensorProduct([38;5;124m"[39m[38;5;124m1o[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m1o[39m[38;5;124m"[39m, [[38;5;124m'[39m[38;5;124m2e[39m[38;5;124m'[39m], irrep_normalization[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnorm[39m[38;5;124m'[39m)
[1;32m      3[0m y2 [38;5;241m=[39m tp(r, r)

[0;31mNameError[0m: name 's2_grid' is not defined
NameError: name 's2_grid' is not defined

